const IMAGES = {
  splash: require("../images/splash.png"),
  google: require("../images/google.png"),
  fb: require("../images/facebook.png"),
  apple: require("../images/apple.png"),
  potig: require("../images/poti.png"),
  spanish: require("../images/spanish.png"),
  french: require("../images/french.png"),
  eng: require("../images/eng.png"),
  italy: require("../images/italy.png"),
  nutrition: require("../images/Ellipse.png"),
  vaccine: require("../images/Ellipse1.png"),
  bottle: require("../images/Ellipse2.png"),
  community: require("../images/Ellipse3.png"),
  baby: require("../images/Ellipse4.png"),
  internet: require("../images/Ellipse5.png"),
  profile: require("../images/profile.jpg"),
  meal: require("../images/meals.png"),
  foodboard: require("../images/foodboard.png"),
  receipe: require("../images/receipe.png"),
  consltant: require("../images/constalnt.png"),
  recepie1: require("../images/recepie1.png"),
  recepie2: require("../images/recepie2.png"),
  diet1: require("../images/diet1.png"),
  diet2: require("../images/diet2.png"),
  diet3: require("../images/diet3.png"),
  diet4: require("../images/diet4.png"),
  diet5: require("../images/diet5.png"),
  baby1: require("../images/baby1.jpg"),
  baby2: require("../images/baby2.jpg"),
  baby3: require("../images/baby3.jpg"),
  baby4: require("../images/baby4.jpg"),
  child: require("../images/child.png"),
  playing: require("../images/playing.png"),
  prank1: require("../images/prank1.png"),
  prank2: require("../images/prank2.png"),
  prank3: require("../images/prank3.png"),
  prank4: require("../images/prank4.png"),
  vaccination1: require('../images/vaccination1.jpg'),
  vaccination2: require('../images/vaccination2.jpg'),
  vaccination3: require('../images/vaccination3.jpg'),
  vaccination4: require('../images/vaccination4.jpg')
};

export default IMAGES;