import { StyleSheet } from 'react-native';
import COLORS from '../../utils/Colors';
import { horizontalScale, verticalScale } from '../../utils/Metrics';

export default StyleSheet.create({
  linearContainer: {
    flex: 1,
  },
  container: {
    flex: 1,
    backgroundColor: 'transparent',
    paddingHorizontal: horizontalScale(18),
  },
  backBtn: {
    marginTop: verticalScale(8),
    marginLeft: horizontalScale(5),
    alignSelf: 'flex-start',
    position: 'absolute',
    zIndex: 2,
    backgroundColor: 'rgba(255,255,255,0.28)',
    borderRadius: 20,
    paddingHorizontal: 1,
    paddingVertical: 1,
    top: verticalScale(3),
    left: horizontalScale(5),
  },
  profileCircle: {
    borderRadius: 62,
    borderWidth: 2,
    borderColor: COLORS.appLinear2,
    backgroundColor: 'rgba(255,255,255,0.25)',
    width: 124,
    height: 124,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: verticalScale(8),
  },
  avatarWrapper: {
    alignSelf: 'center',
    position: 'relative',
    width: 98,
    height: 98,
    borderRadius: 49,
    backgroundColor: 'rgba(255,255,255,0.29)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatar: {
    width: 92,
    height: 92,
    borderRadius: 46,
    backgroundColor: COLORS.appLinear2,
    borderWidth: 1.5,
    borderColor: COLORS.appLinear2,
  },
  editIconWrapper: {
    position: 'absolute',
    top: -8,
    right: -10,
    backgroundColor: COLORS.appLinear1,
    borderRadius: 19,
    padding: 7,
    borderWidth: 2,
    borderColor: COLORS.White,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.15,
    elevation: 1,
    zIndex: 3,
  },
  profileName: {
    marginTop: verticalScale(16),
    textAlign: 'center',
    fontSize: 23,
    marginBottom: 5,
  },
  profileRole: {
    fontSize: 14,
    color: COLORS.darkgrey,
    textAlign: 'center',
    marginBottom: verticalScale(14),
  },
  editProfileBtnWrap: {
    alignItems: 'center',
    marginVertical: verticalScale(10),
    marginBottom: verticalScale(19),
  },
  editProfileBtn: {
    backgroundColor: COLORS.blue,
    borderRadius: 8,
    paddingVertical: verticalScale(12),
    paddingHorizontal: horizontalScale(36),
    alignItems: 'center',
  },
  listContainer: {
    justifyContent:"center",
    flex:1,
    marginTop: verticalScale(4),
    paddingHorizontal: horizontalScale(12),
  },
  listCard: {
    backgroundColor: COLORS.White,
    borderRadius: 18,
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: verticalScale(12),
    paddingHorizontal: horizontalScale(14),
    marginBottom: verticalScale(10),
    elevation: 2,
    shadowColor: COLORS.black,
    shadowOpacity: 0.07,
    shadowOffset: { width: 0, height: 0.5 },
    gap: 16,
  },
  listTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 2,
  },
});
